// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATsebZWh_0R7WJx8c5Dn2SbzwwC9XAZsI',
    appId: '1:870544938148:web:9daaf35355fcab4d210231',
    messagingSenderId: '870544938148',
    projectId: 'respiracheck-6ffb8',
    databaseURL:
        'https://respiracheck-6ffb8-default-rtdb.asia-southeast1.firebasedatabase.app',
    authDomain: 'respiracheck-6ffb8.firebaseapp.com',
    storageBucket: 'respiracheck-6ffb8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBtDsYKsfz59U6h4-idNQy1BqEIjB4hbo',
    appId: '1:870544938148:android:996079ab466a4c75210231',
    messagingSenderId: '870544938148',
    projectId: 'respiracheck-6ffb8',
    databaseURL:
        'https://respiracheck-6ffb8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'respiracheck-6ffb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCECw1iUgZJ5hefc_4FIKzRxZ7qVGr3UCA',
    appId: '1:870544938148:ios:5d10ca99996adaad210231',
    messagingSenderId: '870544938148',
    projectId: 'respiracheck-6ffb8',
    databaseURL:
        'https://respiracheck-6ffb8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'respiracheck-6ffb8.firebasestorage.app',
    iosBundleId: 'com.example.inspiracheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCECw1iUgZJ5hefc_4FIKzRxZ7qVGr3UCA',
    appId: '1:870544938148:ios:5d10ca99996adaad210231',
    messagingSenderId: '870544938148',
    projectId: 'respiracheck-6ffb8',
    databaseURL:
        'https://respiracheck-6ffb8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'respiracheck-6ffb8.firebasestorage.app',
    iosBundleId: 'com.example.inspiracheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATsebZWh_0R7WJx8c5Dn2SbzwwC9XAZsI',
    appId: '1:870544938148:web:efd0520cd54fbda9210231',
    messagingSenderId: '870544938148',
    projectId: 'respiracheck-6ffb8',
    databaseURL:
        'https://respiracheck-6ffb8-default-rtdb.asia-southeast1.firebasedatabase.app',
    authDomain: 'respiracheck-6ffb8.firebaseapp.com',
    storageBucket: 'respiracheck-6ffb8.firebasestorage.app',
  );
}
